// const x = [
//   {
//     adult: false,
//     backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
//     belongs_to_collection: null,
//     budget: 165000000,
//     genres: [
//       { id: 12, name: "Adventure" },
//       { id: 18, name: "Drama" },
//       { id: 878, name: "Science Fiction" },
//     ],
//     homepage: "http://www.interstellarmovie.net/",
//     id: 157336,
//     imdb_id: "tt0816692",
//     original_language: "en",
//     original_title: "Interstellar",
//     overview:
//       "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
//     popularity: 150.485,
//     poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
//     production_companies: [
//       {
//         id: 923,
//         logo_path: "/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png",
//         name: "Legendary Pictures",
//         origin_country: "US",
//       },
//       {
//         id: 9996,
//         logo_path: "/3tvBqYsBhxWeHlu62SIJ1el93O7.png",
//         name: "Syncopy",
//         origin_country: "GB",
//       },
//       {
//         id: 13769,
//         logo_path: null,
//         name: "Lynda Obst Productions",
//         origin_country: "",
//       },
//     ],
//     production_countries: [
//       { iso_3166_1: "GB", name: "United Kingdom" },
//       { iso_3166_1: "US", name: "United States of America" },
//     ],
//     release_date: "2014-11-05",
//     revenue: 701729206,
//     runtime: 169,
//     spoken_languages: [
//       { english_name: "English", iso_639_1: "en", name: "English" },
//     ],
//     status: "Released",
//     tagline: "Mankind was born on Earth. It was never meant to die here.",
//     title: "Interstellar",
//     video: false,
//     vote_average: 8.42,
//     vote_count: 32927,
//     videos: {
//       results: [
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "INTERSTELLAR - Own it TODAY on Blu-ray and DIGITAL HD!",
//           key: "KlyknsTJk0w",
//           published_at: "2015-03-20T21:10:51.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Teaser",
//           official: true,
//           id: "57817ab4c3a36813870024b7",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar – Building A Black Hole – Official Warner Bros.",
//           key: "MfGfZwQ_qaY",
//           site: "YouTube",
//           size: 1080,
//           type: "Featurette",
//           official: true,
//           published_at: "2014-10-24T12:59:28.000Z",
//           id: "5db465f6f056d500180e96ff",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar Movie - Official Trailer 3",
//           key: "0vxOhd4qlnA",
//           published_at: "2014-10-01T21:37:54.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: false,
//           id: "57817accc3a368592500392e",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar – Trailer 4 – Official Warner Bros.",
//           key: "LY19rHKAaAg",
//           published_at: "2014-10-01T19:00:20.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: true,
//           id: "57817b0fc3a368592500394d",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar Movie - Official Trailer 2",
//           key: "Rt2LHkSwdPQ",
//           published_at: "2014-07-31T23:00:58.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: false,
//           id: "5795006f92514142390035ae",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar – Trailer 3 – Official Warner Bros.",
//           key: "ePbKGoIGAXY",
//           published_at: "2014-07-31T23:00:27.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: true,
//           id: "5add84850e0a2608d8009256",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar Movie - Official Trailer",
//           key: "2LqzF5WauAw",
//           published_at: "2014-05-16T17:56:42.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: false,
//           id: "5794fffbc3a36829ab00056f",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar - Trailer - Official Warner Bros. UK",
//           key: "zSWdZVtXT7E",
//           published_at: "2014-05-16T17:00:22.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: true,
//           id: "57817aa69251417bfc000a58",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar Movie - Official Teaser",
//           key: "nyc6RJEEe0U",
//           published_at: "2013-12-14T16:07:52.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: false,
//           id: "57817a91c3a36873ea000adf",
//         },
//         {
//           iso_639_1: "en",
//           iso_3166_1: "US",
//           name: "Interstellar - Teaser Trailer - Official Warner Bros. UK",
//           key: "827FNDpQWrQ",
//           published_at: "2013-12-14T16:00:10.000Z",
//           site: "YouTube",
//           size: 1080,
//           type: "Trailer",
//           official: true,
//           id: "57817ada9251417c28000b02",
//         },
//       ],
//     },
//   },
// ];

// const upComingMovies = [
//   {
//     adult: false,
//     backdrop_path: "/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg",
//     genre_ids: [27, 53],
//     id: 951491,
//     original_language: "en",
//     original_title: "Saw X",
//     overview:
//       "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
//     popularity: 755.378,
//     poster_path: "/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg",
//     release_date: "2023-09-26",
//     title: "Saw X",
//     video: false,
//     vote_average: 7.416,
//     vote_count: 1088,
//   },
//   {
//     adult: false,
//     backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
//     genre_ids: [28, 18],
//     id: 678512,
//     original_language: "en",
//     original_title: "Sound of Freedom",
//     overview:
//       "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
//     popularity: 698.689,
//     poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
//     release_date: "2023-07-03",
//     title: "Sound of Freedom",
//     video: false,
//     vote_average: 8.093,
//     vote_count: 1478,
//   },
//   {
//     adult: false,
//     backdrop_path: "/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg",
//     genre_ids: [28, 53, 80],
//     id: 762430,
//     original_language: "en",
//     original_title: "Retribution",
//     overview:
//       "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks- all with his kids trapped in the back seat.",
//     popularity: 594.316,
//     poster_path: "/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg",
//     release_date: "2023-08-23",
//     title: "Retribution",
//     video: false,
//     vote_average: 6.975,
//     vote_count: 671,
//   },
//   {
//     adult: false,
//     backdrop_path: "/azD31DjpV3PJfjF3h72LVw2WCSD.jpg",
//     genre_ids: [27],
//     id: 807172,
//     original_language: "en",
//     original_title: "The Exorcist: Believer",
//     overview:
//       "When two girls disappear into the woods and return three days later with no memory of what happened to them, the father of one girl seeks out Chris MacNeil, who's been forever altered by what happened to her daughter fifty years ago.",
//     popularity: 563.412,
//     poster_path: "/fFXkAlMH2iQrNknv4eq7LGTkcti.jpg",
//     release_date: "2023-10-04",
//     title: "The Exorcist: Believer",
//     video: false,
//     vote_average: 6.159,
//     vote_count: 577,
//   },
//   {
//     adult: false,
//     backdrop_path: "/xgGGinKRL8xeRkaAR9RMbtyk60y.jpg",
//     genre_ids: [16, 10751, 10402, 14, 35],
//     id: 901362,
//     original_language: "en",
//     original_title: "Trolls Band Together",
//     overview:
//       "When Branch’s brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
//     popularity: 435.208,
//     poster_path: "/lxoPJR6eR5nd6nHSKIkEIV4FQWe.jpg",
//     release_date: "2023-10-12",
//     title: "Trolls Band Together",
//     video: false,
//     vote_average: 6.6,
//     vote_count: 49,
//   },
//   {
//     adult: false,
//     backdrop_path: "/jP3FatCTHc460ZGW57q9ypTdBqu.jpg",
//     genre_ids: [53, 878, 28],
//     id: 937249,
//     original_language: "en",
//     original_title: "57 Seconds",
//     overview:
//       "When a tech blogger lands an interview with a tech guru and stops an attack on him, he finds a mysterious ring that takes him back 57 seconds into the past.",
//     popularity: 295.748,
//     poster_path: "/dfS5qHWFuXyZQnwYREwb7N4qU5p.jpg",
//     release_date: "2023-09-29",
//     title: "57 Seconds",
//     video: false,
//     vote_average: 5.757,
//     vote_count: 187,
//   },
//   {
//     adult: false,
//     backdrop_path: "/6WFfCMe7J7FxsnlHEo1wzU2JH6s.jpg",
//     genre_ids: [80, 18, 36],
//     id: 466420,
//     original_language: "en",
//     original_title: "Killers of the Flower Moon",
//     overview:
//       "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.",
//     popularity: 237.69,
//     poster_path: "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
//     release_date: "2023-10-18",
//     title: "Killers of the Flower Moon",
//     video: false,
//     vote_average: 7.7,
//     vote_count: 965,
//   },
//   {
//     adult: false,
//     backdrop_path: "/igwshQHV36aBkPyWp7En5P4Kn2V.jpg",
//     genre_ids: [27, 53, 9648],
//     id: 1071215,
//     original_language: "en",
//     original_title: "Thanksgiving",
//     overview:
//       "After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.",
//     popularity: 206.755,
//     poster_path: "/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg",
//     release_date: "2023-11-16",
//     title: "Thanksgiving",
//     video: false,
//     vote_average: 6.104,
//     vote_count: 24,
//   },
//   {
//     adult: false,
//     backdrop_path: "/9sl9k7FjE4g0vCVNkPdR1Fs3Yx8.jpg",
//     genre_ids: [36, 18, 10752],
//     id: 753342,
//     original_language: "en",
//     original_title: "Napoleon",
//     overview:
//       "A personal look at the French military leader’s origins and swift, ruthless climb to emperor, viewed through the prism of Napoleon’s addictive, volatile relationship with his wife and one true love, Josephine.",
//     popularity: 217.808,
//     poster_path: "/s46YI7diwlqDVLe55uOaO1VzTId.jpg",
//     release_date: "2023-11-22",
//     title: "Napoleon",
//     video: false,
//     vote_average: 6.2,
//     vote_count: 4,
//   },
//   {
//     adult: false,
//     backdrop_path: "/1HzL603WOer58xtnrRYdSIL5K04.jpg",
//     genre_ids: [35, 12],
//     id: 912908,
//     original_language: "en",
//     original_title: "Strays",
//     overview:
//       "When Reggie is abandoned on the mean city streets by his lowlife owner, Doug, Reggie is certain that his beloved owner would never leave him on purpose. But once Reggie falls in with Bug, a fast-talking, foul-mouthed stray who loves his freedom and believes that owners are for suckers, Reggie finally realizes he was in a toxic relationship and begins to see Doug for the heartless sleazeball that he is.",
//     popularity: 178.94,
//     poster_path: "/muDaKftykz9Nj1mhRheMdbuNI9Z.jpg",
//     release_date: "2023-08-17",
//     title: "Strays",
//     video: false,
//     vote_average: 7.5,
//     vote_count: 520,
//   },
//   {
//     adult: false,
//     backdrop_path: "/rron9HAuS9s7zBF8iCX1tsafxUo.jpg",
//     genre_ids: [18, 10749],
//     id: 666277,
//     original_language: "en",
//     original_title: "Past Lives",
//     overview:
//       "Nora and Hae Sung, two childhood friends, are reunited in New York for one fateful week as they confront notions of destiny, love, and the choices that make a life.",
//     popularity: 162.034,
//     poster_path: "/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
//     release_date: "2023-06-02",
//     title: "Past Lives",
//     video: false,
//     vote_average: 7.937,
//     vote_count: 285,
//   },
//   {
//     adult: false,
//     backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
//     genre_ids: [16, 10751, 14, 12],
//     id: 1022796,
//     original_language: "en",
//     original_title: "Wish",
//     overview:
//       "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
//     popularity: 171.911,
//     poster_path: "/8QtDhh8mnGUEyrJsaeb3kYgDRaA.jpg",
//     release_date: "2023-11-13",
//     title: "Wish",
//     video: false,
//     vote_average: 7.0,
//     vote_count: 6,
//   },
//   {
//     adult: false,
//     backdrop_path: "/f9ErVXAyR9EP5WOOp4i5ivBKsKC.jpg",
//     genre_ids: [35],
//     id: 814776,
//     original_language: "en",
//     original_title: "Bottoms",
//     overview:
//       "Unpopular best friends PJ and Josie start a high school self-defense club to meet girls and lose their virginity. They soon find themselves in over their heads when the most popular students start beating each other up in the name of self-defense.",
//     popularity: 152.613,
//     poster_path: "/jeyTQrNEpyE1LZIgVlswYh3sc34.jpg",
//     release_date: "2023-08-25",
//     title: "Bottoms",
//     video: false,
//     vote_average: 6.989,
//     vote_count: 176,
//   },
//   {
//     adult: false,
//     backdrop_path: "/dp0rdbGSbZTyWumnbWspXQp87hA.jpg",
//     genre_ids: [27, 9648],
//     id: 1024773,
//     original_language: "en",
//     original_title: "It Lives Inside",
//     overview:
//       "Desperate to fit in at school, Sam rejects her East Indian culture and family to be like everyone else. However, when a mythological demonic spirit latches onto her former best friend, she must come to terms with her heritage to defeat it.",
//     popularity: 154.646,
//     poster_path: "/73gIfV8gDwkVgUrFDzt4TfZC9Zc.jpg",
//     release_date: "2023-09-06",
//     title: "It Lives Inside",
//     video: false,
//     vote_average: 5.695,
//     vote_count: 82,
//   },
//   {
//     adult: false,
//     backdrop_path: "/hb0BeFvZNx2zLGWwuwENOIVeK1U.jpg",
//     genre_ids: [35, 18, 36],
//     id: 792293,
//     original_language: "en",
//     original_title: "Dumb Money",
//     overview:
//       "Vlogger Keith Gill sinks his life savings into GameStop stock and posts about it. When social media starts blowing up, so do his life and the lives of everyone following him. As a stock tip becomes a movement, everyone gets rich—until the billionaires fight back, and both sides find their worlds turned upside down.",
//     popularity: 98.504,
//     poster_path: "/xYTymnjkVqhn3V66QmNJxFUesLT.jpg",
//     release_date: "2023-09-15",
//     title: "Dumb Money",
//     video: false,
//     vote_average: 6.652,
//     vote_count: 99,
//   },
//   {
//     adult: false,
//     backdrop_path: "/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
//     genre_ids: [28, 12, 53],
//     id: 646389,
//     original_language: "en",
//     original_title: "Plane",
//     overview:
//       "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
//     popularity: 113.346,
//     poster_path: "/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg",
//     release_date: "2023-01-12",
//     title: "Plane",
//     video: false,
//     vote_average: 6.989,
//     vote_count: 1847,
//   },
//   {
//     adult: false,
//     backdrop_path: "/hjyqNFHx5wIO8dqaRi0v2ix1wiR.jpg",
//     genre_ids: [53, 28, 80, 27],
//     id: 808396,
//     original_language: "en",
//     original_title: "God Is a Bullet",
//     overview:
//       "Based on true events and the novel of the same name. Vice detective Bob Hightower finds his ex-wife murdered and daughter kidnapped by a cult. Frustrated by the botched official investigations, he quits the force and infiltrates the cult to hunt down the leader with the help of the cult’s only female victim escapee, Case Hardin.",
//     popularity: 94.964,
//     poster_path: "/5kiLS9nsSJxDdlYUyYGiSUt8Fi8.jpg",
//     release_date: "2023-06-22",
//     title: "God Is a Bullet",
//     video: false,
//     vote_average: 6.315,
//     vote_count: 108,
//   },
//   {
//     adult: false,
//     backdrop_path: "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
//     genre_ids: [16, 12, 14, 18],
//     id: 508883,
//     original_language: "ja",
//     original_title: "君たちはどう生きるか",
//     overview:
//       "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
//     popularity: 82.726,
//     poster_path: "/y9xS5NQTBnFjDoXhSFQeGxlmkoM.jpg",
//     release_date: "2023-07-14",
//     title: "The Boy and the Heron",
//     video: false,
//     vote_average: 7.22,
//     vote_count: 173,
//   },
//   {
//     adult: false,
//     backdrop_path: "/uIk2g2bRkNwNywKZIhC5oIU94Kh.jpg",
//     genre_ids: [35, 10751, 14],
//     id: 787699,
//     original_language: "en",
//     original_title: "Wonka",
//     overview:
//       "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
//     popularity: 86.523,
//     poster_path: "/dbABBH3DvFLkBUKwPUG0BlTYdmh.jpg",
//     release_date: "2023-12-06",
//     title: "Wonka",
//     video: false,
//     vote_average: 0.0,
//     vote_count: 0,
//   },
//   {
//     adult: false,
//     backdrop_path: "/x0kI3Tbaqe6OqHXrOJDJ4c4SycM.jpg",
//     genre_ids: [28, 18, 878],
//     id: 940721,
//     original_language: "ja",
//     original_title: "ゴジラ-1.0",
//     overview:
//       "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?",
//     popularity: 71.977,
//     poster_path: "/kM5FcckjKbWSeV9Gj0hBTpvNuvi.jpg",
//     release_date: "2023-11-03",
//     title: "Godzilla Minus One",
//     video: false,
//     vote_average: 7.4,
//     vote_count: 5,
//   },
// ];
